### ISSUE TITLE
Upgrade to 0.6.0 broken

### ISSUE THREAD

**Issue by joffotron** [cconover/wp-featured-image-caption#19]
I've just upgraded from 0.4.0 -> 0.5.0 -> 0.6.0, and I'm now seeing this in my error log:

`PHP Fatal error:  Call to a member function auto_append() on a non-object in /nas/wp/www/cluster-3078/artplustech/wp-content/plugins/featured-image-caption/featured-image-caption.php on line 51`

**Comment by cconover** [comment]
I'm patching that now, 0.6.1 will be available in a few minutes. Sorry about that.

**Comment by joffotron** [comment]
:+1:
