### ISSUE TITLE
Problem displaying Caption/Source text with quote (") characters

### ISSUE THREAD

**Issue by joffotron** [cconover/wp-featured-image-caption#22]
I often find when I go to edit my posts again after saving them, that the Caption and/or (more often) the source text fields are blank.

I can't be sure, but this seems to be more common when those fields are saved with quote characters in them, and looking in the DB at the post metadata, it doesn't look like there's any escaping going on.

Not being super familiar with WP development, should this be the case? Or is there another, more subtle bug at work here?

**Comment by cconover** [comment]
That's interesting. I'll have to do some testing on that, there very well may be escaping I overlooked. Thanks!

**Comment by joffotron** [comment]
I've tested it in my env, and it looks like it's working as expected now, thanks!
