### ISSUE TITLE
0.6.2 won't activate

### ISSUE THREAD

**Issue by crankyjules** [cconover/wp-featured-image-caption#24]
I get this fatal error:
Parse error: syntax error, unexpected T_STRING in /home1/dragonf3/public_html/manningcommunitynews/wp-content/plugins/featured-image-caption/featured-image-caption.php on line 22

**Comment by cconover** [comment]
Does this happen when you try to activate the plugin, or after it's been activated and you're trying to use it?

**Comment by cconover** [comment]
This should be resolved as of 0.8.0.
