### ISSUE TITLE
Request: Open Source Attribution URL in new page

### ISSUE THREAD

**Issue by avluis** [cconover/wp-featured-image-caption#9]
Is it possible to add a checkbox next to the URL attribute to open the link on a new page.
I can do this by modifying the plugin file, but I would love to have that built-in instead.
My little hack comes undone after each update though.

Oh, and I can confirm that it works deliciously with Wordpress 4.1.

**Comment by cconover** [comment]
Great idea! I'll add this to the next release.

**Comment by avluis** [comment]
Awesome! I have one more for you, give me a bit to post it (I want to describe it properly).

**Comment by avluis** [comment]
Awesome! Thanks again!
